version: "3"

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    networks:
      - listpocket-dev

  front:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-frontend"]
    ports:
      - "8080:8080"
    environment:
      - LISTMONK_API_URL=http://backend:9000
    volumes:
      - ../:/app
    networks:
      - listpocket-dev

  backend:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-backend-docker"]
    ports:
      - "9000:9000"
    volumes:
      - ../:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - listpocket-dev

networks:
  listpocket-dev:
